### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by rabernat** [MITgcm/xmitgcm#238]
We are long overdue for a release. I'd like to get one out asap. I'd like it to include the following PRs:

- [x] Fix llcreader klevels bug #225 @rabernat
- [x] llcreader + ASTE Release 1 #231 @timothyas 
- [x] fixed probable typo for 'coordinate' entry in dimensions dictionary #236 @ifenty 
- [x] feat: IMPLEMENTS CHECKING FOR VARIABLE MATES #237 @fraserwg
- [x] add metadata to llcreader dimensions #239 @rabernat
- [x] update "what's new"
 
I appreciate everyone's work on xmitgcm. These are all quite close, so let's get them over the finish line!

**Comment by AaronDavidSchneider** [comment]
Is there any way that PR #98 could be resurrected and included?

**Comment by rabernat** [comment]
@AaronDavidSchneider -- thanks for your input! We really want to support you.

#98 is quite complex, and no one is working on it right now. We need to make a release very soon, because there are some major bugs that have been fixed on master but not yet released. Nothing prevents us from releasing 0.5 without #98 and then releasing 0.5.1 or 0.6 shortly thereafter.

The main challenge with #98 is that it was abandoned by its author before it was complete. If you are motivated, you could try to pick it up and work it on it. Or you could start from scratch. We would be happy to support you.

**Comment by raphaeldussin** [comment]
@rabernat I left PR #98 on the back burner for so long it fell behind the stove :(
I'm gonna fix the conflicts and get it to a point where it is functioning, but I'd be happy if someone else
could help finishing with the testing,...

**Comment by rabernat** [comment]
That's fantastic @raphaeldussin! Thanks so much. If you can resolve the conflicts, we can take it over.

**Comment by AaronDavidSchneider** [comment]
Thanks for your quick reply!

> I'm gonna fix the conflicts and get it to a point where it is functioning, but I'd be happy if someone else
> could help finishing with the testing,...

Yes I would love to help there.

**Comment by rabernat** [comment]
v0.5.0 has been released to pypi! Conda forge build should soon be triggered. Thanks everyone!!!

@AaronDavidSchneider - we will keep working on cubed-sphere and get another release out asap once that is ready.

**Comment by rabernat** [comment]
p.s. Would someone be willing to make an announcement about the release on the mitgcm mailing list? Maybe @timothyas or @cspencerjones?

**Comment by timothyas** [comment]
Woohoo! Thanks @rabernat for releasing and everyone for contributing! I just sent an announcement to mitgcm-support.

**Comment by edoddridge** [comment]
Great work! And thanks @timothyas for the mailing list announcement.
